name: My Target Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    inputs:
      test_name:
        description: 'Test name in deploy directory'
        required: true
        type: string
    types: [trigger-workflow]

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
