name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Output artifact URL
        run:  echo 'Artifact URL is ${{ github.event.client_payload.artifactURL }}'
