name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Output artifact URL
        run:  echo 'Artifact URL is ${{ github.event.client_payload.artifactURL }}'

      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="diggioorg02" 
          repo_name="worflowremote"  
          event_type="trigger-workflow"
          artifactURL="${{ steps.artifact-k6-upload.outputs.artifact-url }}"
  
          curl -L --output k6.zip \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{artifactURL}}"
