name: My Target Multi Workflow
run-name: Receiving from Workflow parent runID ${{github.event.client_payload.distinct_id }}
on:
  repository_dispatch:
    types: [trigger-multiworkflow]

    
jobs:
  k6onpod:
    strategy:
      matrix:
        npod: ${{ github.event.client_payload.numpods }}
        k6cmd: ${{ github.event.client_payload.k6cmd }}
        
    runs-on: ubuntu-latest

    steps:
      - name: Output artifact URL
        run:  echo 'Artifact URL is ${{ github.event.client_payload.artifactURL }}'

      - name: sleep
        run: sleep 10
        
      - name: numero pod ${{ matrix.npod }}
        run: echo 'k6 md no pod é ${{ matrix.k6cmd }}'
