name: My Target Workflow
run-name: Receiving from Workflow parent runID ${{github.event.client_payload.distinct_id }}
on:
  repository_dispatch:
    types: [trigger-workflow]

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: IDs
        run:  echo 'ID ${{ github.run_id }} origin ${{github.event.client_payload.distinct_id }} '

      - name: show payload
        run: |
          echo "${{github.event.client_payload.k6cmd }}"
          echo "${{github.event.client_payload.zipfile }}"
          echo "${{github.event.client_payload.file }}"
  

      - name: Check K6 artifact
        run: file k6.zip

      - name: unzip K6 artifact
        run: sleep 20
        
      - name: list K6 artifact
        run: ls -ilha .
