name: My Target Workflow
run-name: Receiving from Workflow parent runID ${{github.event.client_payload.distinct_id }}
on:
  repository_dispatch:
    types: [trigger-workflow]

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: IDs
        run:  echo 'ID ${{ github.run_id }} origin ${{github.event.client_payload.distinct_id }} '

      - name: "show payload ${{github.event.client_payload.k6cmd }}"
        run: |
          echo "${{github.event.client_payload.file }}"
  
      - name: "Set env"
        run: echo "GITHUB_FILEZIP=$(echo ${{github.event.client_payload.file }})" >> $GITHUB_ENV

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import base64
            import os

            fileziped = os.environ['GITHUB_FILEZIP']
            print(fileziped)
            b64fileziped_bytes = base64.b64decode(fileziped.encode("utf-8"))
            print(b64fileziped_bytes)

            with open("k6.zip", "wb") as file:
              file.write(b64fileziped_bytes)


      - name: Check K6 artifact
        run: file k6.zip

      - name: unzip K6 artifact
        run: sleep 20
        
      - name: list K6 artifact
        run: ls -ilha .
